import streamlit as st
import uuid
from utils.database import create_conversation, save_message, log_search
from utils.ai_model import is_using_fallback, explain_disease, get_model_name
from utils.styles import inject_base_css, callout

st.set_page_config(page_title="Disease Explainer", page_icon="🔬", layout="wide")
inject_base_css()

if "session_id" not in st.session_state:
    st.session_state.session_id = str(uuid.uuid4())
if "disease_history" not in st.session_state:
    st.session_state.disease_history = []

st.title("🔬 Disease Explainer")
st.caption("Search any disease or medical condition and get a plain-English explanation.")

st.markdown("### Common conditions")
common = [
    "Diabetes", "Hypertension", "Asthma", "Anemia",
    "Arthritis", "Depression", "Migraine", "GERD",
    "Hypothyroidism", "COVID-19", "Dengue", "Malaria",
]
cols = st.columns(4)
for i, disease in enumerate(common):
    if cols[i % 4].button(disease, key=f"common_{i}"):
        st.session_state["disease_prefill"] = disease

st.divider()

prefill = st.session_state.pop("disease_prefill", "")
with st.form("disease_form"):
    col1, col2 = st.columns([4, 1])
    with col1:
        disease_input = st.text_input(
            "Search disease or condition:",
            value=prefill,
            placeholder="e.g. Type 2 Diabetes, Parkinson's disease, Celiac disease…",
        )
    with col2:
        st.markdown("<br>", unsafe_allow_html=True)
        search_btn = st.form_submit_button("Explain →", use_container_width=True)

if search_btn and disease_input.strip():
    disease = disease_input.strip()
    log_search(st.session_state.session_id, "disease", disease)

    with st.spinner(f"Looking up '{disease}'…"):
        explanation = explain_disease(disease)

    st.session_state.disease_history.insert(0, {"disease": disease, "explanation": explanation})

    conv_id = create_conversation(st.session_state.session_id, "disease")
    save_message(conv_id, "user", f"Explain: {disease}")
    save_message(conv_id, "assistant", explanation)

if st.session_state.disease_history:
    latest = st.session_state.disease_history[0]

    st.markdown(f"## 📋 {latest['disease']}")
    st.markdown(f"<div class='result-box'>{latest['explanation']}</div>", unsafe_allow_html=True)

    callout(
        "<strong>Disclaimer:</strong> This explanation is generated by AI for educational purposes only. "
        "Always consult a qualified healthcare professional for medical advice.",
        kind="warn",
    )

    col1, col2 = st.columns(2)
    with col1:
        st.download_button(
            "📥 Download explanation",
            data=f"Disease: {latest['disease']}\n\n{latest['explanation']}",
            file_name=f"{latest['disease'].replace(' ', '_')}_info.txt",
            mime="text/plain",
            use_container_width=True,
        )
    with col2:
        if st.button("🔍 Ask follow-up in FAQ Chat", use_container_width=True):
            st.session_state["faq_prefill"] = f"Tell me more about {latest['disease']}"
            st.switch_page("pages/1_💬_FAQ_Chatbot.py")

    if len(st.session_state.disease_history) > 1:
        st.divider()
        st.markdown("### 🕑 Recent searches this session")
        for entry in st.session_state.disease_history[1:6]:
            with st.expander(f"📌 {entry['disease']}"):
                st.markdown(entry["explanation"])

else:
    st.info("🔬 Search for a disease above to get a clear explanation.")

with st.sidebar:
    st.markdown(f"**Model:** `{get_model_name()}`")
    if is_using_fallback():
        callout(
            "The primary AI model failed to load, so answers are currently coming from a "
            "lower-quality fallback model. Check the app logs for the load error.",
            kind="danger",
        )
    st.divider()
    st.markdown("### 🕑 Session searches")
    if st.session_state.disease_history:
        for e in st.session_state.disease_history[:8]:
            st.markdown(f"- {e['disease']}")
    else:
        st.caption("None yet.")

    st.divider()
    st.markdown("""
    **What you'll learn:**
    - What the condition is
    - Common causes & risk factors
    - Typical symptoms
    - General treatment options
    """)
    callout("For diagnosis, see a doctor.", kind="warn")
